link_shortener/models.py
from .extensions import db
from datetime import datetime
import random

class Link(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	original_url = db.Column(db.String(1000))
	short_url = db.Column(db.String(7), unique = True)
	create_date = db.Column(db.DateTime, default=datetime.now)

	def __init__(self,**kwargs):
		super().__init__(**kwargs)

		check_org_url = self.query.filter_by(original_url=self.original_url).first()

		#if the url passed has already been shortened just return 
		#that one instead of generating a new one
		if self.original_url != check_org_url:
			self.short_url = self.short_link_gen()

		else:
			self.short_url = check_org_url.short_url

	def short_link_gen(self):
		no = random.randrange(0,10000000000)
		short_url = ''.join(str(no))

		link = self.query.filter_by(short_url=short_url).first()

		#if generated link already exists make new one
		if link:
			return self.short_link_gen()

		else:
			return short_url

link_shortener/__init__.py
from flask import Flask
from .extensions import db
from .routes import short

def create_app(config_file="settings.py"):
	app = Flask(__name__)

	app.config.from_pyfile(config_file)
	db.init_app(app)
	app.register_blueprint(short)

	return app

link_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .extensions import db
from .models import  Link

short = Blueprint("short", __name__)

@short.route('/<short_url>')
def url_redirect(short_url):
	link = Link.query.filter_by(short_url=short_url).first_or_404()
	return redirect(link.original_url)

@short.route('/')
def index():
	return render_template('index.html')

@short.route('/send_link', methods=['POST'])
def send_link():
	original_url = request.form['original_url']
	link = Link(original_url=original_url)
	db.session.add(link)
	db.session.commit()

	return render_template('short_link.html', new = link.short_url, original_url = link.original_url)

@short.errorhandler(404)
def error_page(error):
	return render_template('404.html')

link_shortener/templates/index.html
</br></br><h4>ENTER LINK</h4>
<center><form method="POST" action="{{ url_for('short.send_link') }}">
	<input type="text" name="original_url"></br></br>
	<button type="submit">SUBMIT</button>
</form></center>

<style>
	h4{
		font-family: Tahoma;
		margin-left: 35px;
	}
	input {
  width: 95%;
  height: 40px;
  border: 2px solid turquoise;
  border-radius: 4px;
}
button{
  border-radius: 10px;
  height: 40px;
  width: 150px;
  background-color: Transparent;
  border-style: solid;
}

button:hover {
  background-color: #4CAF50;;
  color:white;
}
</style>

link_shortener/templates/short_link.html

</br></br><h4>OLD LINK</h4>
<center><form >
	<input type="text" name="original_url" value = "{{original_url}}"></br></br>
	</form></center>

</br></br><h4>SHORT LINK</h4>
<center><form >
	<input id = "myInput" type="text" name="new" value="{{url_for('short.url_redirect',short_url = new, _external=True)}}"></br></br>
</form></center>



<style>
	h4{
		font-family: Tahoma;
		margin-left: 35px;
	}
	input {
  width: 95%;
  height: 40px;
  border: 2px solid turquoise;
  border-radius: 4px;
}
</style>